### ISSUE TITLE
Update README w/ Instructions

### ISSUE THREAD

**Issue by Elte156** [seanpcook/WebRTCLab#1]
https://raw.githubusercontent.com/seanpcook/WebRTCLab/master/README.md

Not sure how to run this application.
It's missing certs.

```console
PS C:\Users\Tony\github\WebRTCLab> node .\index.js
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'certs/key.pem'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Object.<anonymous> (C:\Users\Tony\github\WebRTCLab\index.js:7:11)  
    at Module._compile (internal/modules/cjs/loader.js:1133:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:
1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)      
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/
run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'certs/key.pem'
}
PS C:\Users\Tony\github\WebRTCLab> 
```

**Comment by seanpcook** [comment]
Certs are added as well as a package.json file with dependencies.
